name: Build Flet APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Обновлено на v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Обновлено на v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "flet[build]"

      - name: Build APK
        run: flet build apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4 # Обновлено на v4 (это и было причиной ошибки)
        with:
          name: TrackerApp-Release
          path: build/app/outputs/flutter-apk/app-release.apk
